/*
 * File: app/store/MyJsonTreeStore.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.MyJsonTreeStore', {
    extend: 'Ext.data.TreeStore',

    requires: [
        'MyApp.model.VblockModel'
    ],

    config: {
        model: 'MyApp.model.VblockModel',
        storeId: 'MyJsonTreeStore',
        defaultRootProperty: 'items',
        root: {
            items: [
                {
                    text: 'Drinks',
                    items: [
                        {
                            text: 'Water',
                            items: [
                                {
                                    text: 'Still',
                                    leaf: true
                                },
                                {
                                    text: 'Sparkling',
                                    leaf: true
                                }
                            ]
                        },
                        {
                            text: 'Soda',
                            leaf: true
                        }
                    ]
                },
                {
                    text: 'Snacks',
                    items: [
                        {
                            text: 'Nuts',
                            leaf: true
                        },
                        {
                            text: 'Pretzels',
                            leaf: true
                        },
                        {
                            text: 'Wasabi Peas',
                            leaf: true
                        }
                    ]
                }
            ]
        }
    }
});