
/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is 
 * provided to support globbing requires, custom xtypes, and other 
 * metadata-driven class system features 
 */
Ext.Loader.addClassPathMappings({
  "Ext": "touch/src",
  "Ext.data.ProxyMgr": "touch/src/app/Application.js",
  "Ext.device.Purchases.Product": "touch/src/device/purchases/Sencha.js",
  "Ext.device.Purchases.Purchase": "touch/src/device/purchases/Sencha.js",
  "Ext.device.SQLite.Database": "touch/src/device/sqlite/Sencha.js",
  "Ext.device.SQLite.SQLResultSet": "touch/src/device/sqlite/Sencha.js",
  "Ext.device.SQLite.SQLResultSetRowList": "touch/src/device/sqlite/Sencha.js",
  "Ext.device.SQLite.SQLTransaction": "touch/src/device/sqlite/Sencha.js",
  "MyApp": "app",
  "vblocknav": "app"
});
Ext.ClassManager.addNameAlternateMappings({
  "MyApp.controller.AppController": [],
  "MyApp.controller.NavSheetController": [],
  "MyApp.controller.VblockRESTController": [],
  "MyApp.model.PropertyModel": [],
  "MyApp.model.TreeModel": [],
  "MyApp.model.VMModel": [],
  "MyApp.model.VblockModel": [],
  "MyApp.store.MyJsonTreeStore": [],
  "MyApp.store.PropertyStore": [],
  "MyApp.store.VblockTreeStore": [],
  "MyApp.view.DynamicList": [],
  "MyApp.view.MainContainer": [],
  "vblocknav.view.Main": []
});
Ext.ClassManager.addNameAliasMappings({
  "MyApp.controller.AppController": [],
  "MyApp.controller.NavSheetController": [],
  "MyApp.controller.VblockRESTController": [],
  "MyApp.model.PropertyModel": [],
  "MyApp.model.TreeModel": [],
  "MyApp.model.VMModel": [],
  "MyApp.model.VblockModel": [],
  "MyApp.store.MyJsonTreeStore": [],
  "MyApp.store.PropertyStore": [],
  "MyApp.store.VblockTreeStore": [],
  "MyApp.view.DynamicList": [
    "widget.mynestedlist15"
  ],
  "MyApp.view.MainContainer": [],
  "vblocknav.view.Main": [
    "widget.main"
  ]
});
