/*
 * File: app/controller/AppController.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.AppController', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            mainContainer: '#main-container'
        }
    },

    doOrientationChange: function(newOrientation) {
        console.log("orientation changed to " + newOrientation);

        var main = this.getMainContainer();

        var portrait = main.down("#portrait");
        var landscape = main.down("#landscape");

        var list = portrait.down('#vblock-list') || landscape.down('#vblock-list');
        var spcont = portrait.down('#spacetree-container') || landscape.down('#spacetree-container');
        var toolbar = portrait.down('#header-bar') || landscape.down('#header-bar');

        portrait.removeAll(false, true);
        landscape.removeAll(false, true);
        list.remove(toolbar, false);

        var target = landscape;

        if(newOrientation == 'portrait') {
            target = portrait;
            list.add(toolbar);
        } else {
            landscape.add(toolbar);
        }
        target.add(list);
        target.add(spcont);
        main.setActiveItem(target);

    }

});