/*
 * File: app/controller/VblockRESTController.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.VblockRESTController', {
    extend: 'Ext.app.Controller',

    config: {
        visionURL: 'https://fm-sim-nimsoft.internal.superna.net:8443',
        visionUser: 'admin',
        visionPass: 'dangerous'
    },

    getServiceTicketAndResource: function(url) {
        var me = this;

        alert("getting service ticket");

        // need to wait until a ticket granting ticket exists. 
        if(!me.ticketGrantingTicket) {
            Ext.defer(me.fetchVBlockXML, 50, this);
            return;
        }

        alert ("got service ticket, getting aontoher ciket")
        alert(me.ticketGrantingTicket);

        // NExt, get a service ticket. 
        Ext.Ajax.request({
            method: 'POST',
            url: me.ticketGrantingTicket,
            params: {
                service: me.visionURL + url
            },
            useDefaultXhrHeader: false,
            success: function(data) {        
                alert(data.responseText); 
                // fetch the resource on success.
                me.getResource(url, data.responseText);
            }
        });


    },

    getResource: function(url, ticket) {

        alert("getting respource");

        url = this.config.visionURL + url;

        if(ticket) {
            url = url +"?ticket=" + ticket;
        }

        var me = this;
        Ext.Ajax.request({
            method: 'GET',
            url: url,
            useDefaultXhrHeader: false,
            success: function(data) {        
                alert(data.responseText); 
            }
        });

    },

    doLogin: function() {
        var me = this;

        var cas = me.config.visionURL + "/cas/v1/tickets";
        var base = "/fm";


        Ext.Ajax.request({
            method: 'POST',
            url: cas,
            params: {
                username: me.config.visionUser,
                password: me.config.visionPass
            },
            useDefaultXhrHeader: false,
            success: function(data) {        
                var el = document.createElement('div');
                el.innerHTML = data.responseText;        
                var list = el.getElementsByTagName('form');
                me.ticketGrantingTicket = list[0].action;
                me.getServiceTicketAndResource(base);
            }
        });
    },

    init: function(application) {
        this.doLogin();
    }

});