/*
 * File: app/controller/VblockXMLController.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.VblockXMLController', {
    extend: 'Ext.app.Controller',

    config: {
    },

    fetchVBlockXML: function(url) {
        var me = this;

        // need to wait until a ticket granting ticket exists. 
        if(!me.ticketGrantingtTicket) {
            Ext.defer(me.fetchVBlockXML, 50, this);
            return;
        }

        // NExt, get a service ticket. 

        Ext.Ajax.request({
            method: 'POST',
            url: me.ticketGrantingTicket,
            params: {
                service: url
            },
            useDefaultXhrHeader: false,
            success: function(data) {        
                alert(data.responseText);
            }
        });


    },

    getTicketGrantingTicket: function() {
        var me = this;
        var cas = "https://fm-sim-nimsoft.internal.superna.net:8443/cas/v1/tickets";
        //var cas = "ajax/tickets.xml";
        var params = "username=admin&password=dangerous";

        Ext.Ajax.request({
            method: 'POST',
            url: cas,
            params: {
                username: 'admin',
                password: 'dangerous'
            },
            useDefaultXhrHeader: false,
            success: function(data) {        
                var el = document.createElement('div');
                el.innerHTML = data.responseText;        
                var list = el.getElementsByTagName('form');
                me.ticketGrantingTicket = list[0].action;
            }
        });
    },

    init: function(application) {
        this.getTicketGrantingTicket();
    }

});